spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payroll?useSSL=false
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#netty
netty:
  server:
    host: 127.0.0.1
    tcp-port: 8090
    boss-count: 1
    worker-count: 10
    keep-alive: true
    backlog: 100
